### ISSUE TITLE
packaging error

### ISSUE THREAD

**Issue by victorforissier** [pwa-builder/pwabuilder-android#11]
Hi there,

Maybe it's a total noob question and not an issue. When I package the app on Android Studio code and then upload the the Play Store Console, I get that error : 

"
You need to use a different package name because "microsoft.com.pwa" already exists in Google Play.
"

It is unclear to me what and where do I need to change things in my app folder, isn't PWA Builder supposed to take car of the package name ?

Thanks

**Comment by JudahGabriel** [comment]
This has been fixed; you can now supply your own package name.
