### ISSUE TITLE
Weird large title bar

### ISSUE THREAD

**Issue by deltakosh** [pwa-builder/pwabuilder-android#2]
Hey team, I have this weird large title bar on my android project:
![image](https://user-images.githubusercontent.com/1306056/51218343-cf3af800-18e0-11e9-81dd-495e8bd5d4ac.png)

Website: www.collecto.app

**Comment by boyofgreen** [comment]
yes, if your manifest says "fullscreen" for the display type, then the bar will go away.  I think you have "stand alone" which gives you the bar.  I am guessing that was not your expectation :)

**Comment by deltakosh** [comment]
Nope but this is perfectly fine :)
Thanks team for the quick turn around
