### ISSUE TITLE
Login to onedrive is launched outside of my app

### ISSUE THREAD

**Issue by deltakosh** [pwa-builder/pwabuilder-android#3]
Hey team! Me again:D

So In my app (www.collecto.app) I have a transition to onedrive login page but unfortunately this page is loaded outside of the app (Android)

Can you help?

**Comment by lucaasrojas** [comment]
Hey @deltakosh could add more information about the device you used?

**Comment by deltakosh** [comment]
It was a pixel 3. I fixed that issue by updating the code and testing for some urls before running the web intent.
I think it could make sense to have some kind of a list of internal vs external urls (like in the win10 store manifest)

**Comment by lucaasrojas** [comment]
It seems to be related to the scope patterns in the PwaWebViewClient file. It would be a nice feature to include. Let's leave it as a _Feature Request_.

![image](https://user-images.githubusercontent.com/26610409/55568524-3a24ef80-56d6-11e9-8042-acb531968768.png)

**Comment by JudahGabriel** [comment]
This has since been fixed in the new Android TWA platform.
