### ISSUE TITLE
Back button does not work by default with standard web routing (location api)

### ISSUE THREAD

**Issue by jgw96** [pwa-builder/pwabuilder-android#4]
We need to pass control of the back button to the webview:

```@Override
public boolean onKeyDown(int keyCode, KeyEvent event) {
    if (event.getAction() == KeyEvent.ACTION_DOWN) {
        switch (keyCode) {
            case KeyEvent.KEYCODE_BACK:
                WebView myWebView = (WebView) this.findViewById(R.id.webView);
                if (myWebView.canGoBack()) {
                    myWebView.goBack();
                } else {
                    finish();
                }
                return true;
        }

    }
    return super.onKeyDown(keyCode, event);
}
 ```

**Comment by Foovanadil** [comment]
@jgw96 I think I am having this same issue. I have a PWA built in React that uses the standard react-router to manage navigation. In the mobile browser the Android hardware back button navigates as expected. In the Android TWA app produced by PWABuilder the hardware back button quits the app and goes back to the Android home screen.


Is this the same thing you are describing here? If so, where should this code go? It looks like this might be an Override (despite the missing @Override statement) that should be in MainActivity? 


Any clarification you could provide would be helpful.

**Comment by Foovanadil** [comment]
FYI, for anyone that finds this. What I described above is accurate. To get the back button working correctly in Android app you have to put the above code snippet in the MainActivity.java adding the override directive above it, like this


``` 
@Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (event.getAction() == KeyEvent.ACTION_DOWN) {
            switch (keyCode) {
                case KeyEvent.KEYCODE_BACK:
                    WebView myWebView = (WebView) this.findViewById(R.id.webView);
                    if (myWebView.canGoBack()) {
                        myWebView.goBack();
                    } else {
                        finish();
                    }
                    return true;
            }

        }
        return super.onKeyDown(keyCode, event);
    }
```
