### ISSUE TITLE
App runs in fullscreen mode by default

### ISSUE THREAD

**Issue by jgw96** [pwa-builder/pwabuilder-android#5]
Fullscreen mode is usually only used by a small subsection of apps, most apps will want to show the title bar.

**Comment by lucaasrojas** [comment]
I generated a new app and removed the display mode from the manifest. The app was executed with the title bar.

![image](https://user-images.githubusercontent.com/26610409/55579288-40bf6100-56ee-11e9-97bc-b0cf053236be.png)

There is a method that checks if the manifest has a display mode set and if it is set in fullscreen the app will be shown that way.

![image](https://user-images.githubusercontent.com/26610409/55578945-79126f80-56ed-11e9-93cf-0e668a6d366e.png)

This logic seems to be working. Is the issue related to this?

**Comment by JudahGabriel** [comment]
Replying to
