### ISSUE TITLE
Android packages launches Microsoft home page

### ISSUE THREAD

**Issue by Bmartin2013** [pwa-builder/pwabuilder-android#6]
I built an android app package using PWABuilder. When I tested it using Android Studio, the generated app opens the Microsoft Page, but it keeps the app data, like short title.

 
![image](https://user-images.githubusercontent.com/3893598/55251346-1aea1600-522f-11e9-85b9-9b1f9bc2ee0e.png)

**Comment by kbrons** [comment]
Couldn't reproduce. Might have been a one-time issue with the emulator or Android Studio.
